add_rules("plugin.compile_commands.autoupdate", {outputdir=".vscode"})
add_rules("mode.release", "mode.debug")
set_toolchains("gcc")
set_plat("mingw")

add_requires("sfml", {configs = {audio = true, graphics = false, window = false}})
add_requires("taglib")
target("music_player")
    add_files("src/main.cpp")
    add_includedirs("D:/pthang/msys64/ucrt64/include/slint", "D:/pthang/msys64/ucrt64/include")
    add_linkdirs("D:/pthang/msys64/ucrt64/lib", "discord_social_sdk/bin/release")
    add_links("slint_cpp", "discord_partner_sdk")
    add_packages("sfml", "taglib")
    add_includedirs("ui/build", "discord_social_sdk/include")
    add_syslinks("ole32")
    before_build(function (target)
        os.exec("cmd /c D:/pthang/proj/music_player/build.bat")
    end)